// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tufcdgeyxjnaqkddwyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZmNkZ2V5eGpuYXFrZGR3eWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTgyMzUsImV4cCI6MjA2MzQzNDIzNX0.YD0LUgG31LAe3JSH7EloDTavwAVD29Kqw2x_UhjZGdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);